AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Exclude:
    - Gemfile
    - spec/**/*
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - highline_wrapper.gemspec
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinUsage:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/OptionalBooleanParameter:
  AllowedMethods: method_missing

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SwapValues:
  Enabled: true
