name: GitLeaks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    uses: emmahsax/reusable-github-actions-workflows/.github/workflows/reusable-gitleaks.yml@main
